title: the Simplex theme
logo_img: /assets/img/icons/golasblog_logo.svg
favicon: /assets/favicon.ico
description: description
global_tags: jekyll theme simplex golasblog responsive html5
copyright: © Golasowski 2021

sass:
    style: compressed

webrick:
  headers:
    Cache-Control: "max-age=315360000"
    Access-Control-Allow-Origin: "*"

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
